### ISSUE TITLE
cudnn find in cmake,but not find in make

### ISSUE THREAD

**Issue by ccl-private** [CMU-Perceptual-Computing-Lab/openpose#1684]
cmake .. find cuDNN, but when I run make, it out puts cuDNN not found.

Here is cmake out put .
Found CUDA: /usr (found version "10.2") 
-- Building with CUDA.
-- CUDA detected: 10.2
-- Added CUDA NVCC flags for: sm_61
-- Found cuDNN: ver. 7.6.5 found (include: /usr/lib/cuda/include, library: /usr/lib/cuda/lib64/libcudnn.so)

Here is make out put.
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.71)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. ..)
--   CUDA              :   Yes (ver. 10.2)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Not found

**Comment by gineshidalgo99** [comment]
This one should be fixed now in CUDA 11 for OpenPose. Sorry for skipping it then.

**Comment by BoMingZhao** [comment]
> This one should be fixed now in CUDA 11 for OpenPose. Sorry for skipping it then.

I use cuda 11 but still have this problem.


Here is the cmake output:
>-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 11.2
-- Found cuDNN: ver. 8.1.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- Found cuDNN: ver. 8.1.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)

Here is the make output:
>-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- CUDA detected: 11.2
-- Found cuDNN: ver. ??? found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Error at cmake/Cuda.cmake:227 (message):
  cuDNN version >3 is required.
Call Stack (most recent call first):
  cmake/Cuda.cmake:255 (detect_cuDNN)
  cmake/Dependencies.cmake:85 (include)
  CMakeLists.txt:49 (include)
