### ISSUE TITLE
How to use python api in windows?

### ISSUE THREAD

**Issue by zj6362295** [CMU-Perceptual-Computing-Lab/openpose#667]
I want to use python api in windows10 and I referred to the documentation method, but I failed.
When I execute this file( python openpose-master\python\openpose.py ), The error is as follows:
Traceback (most recent call last):
  File ".\openpose.py", line 12, in <module>
    class OpenPose(object):
  File ".\openpose.py", line 16, in OpenPose
    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/_openpose.so')
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
What should I do?

**Comment by gineshidalgo99** [comment]
Please, see updated instructions (fix pushed a few minutes ago) and post any issue you could find. Thanks

**Comment by zj6362295** [comment]
Thank you for your advice.
I downloaded the latest code and recompiled the code.
I wanted to use Python API, but I still failed.
Or a similar problem:
Traceback (most recent call last):
  File "C:/Users/admin_zj/Desktop/openpose-master/build/python/openpose/openpose.py", line 16, in <module>
    class OpenPose(object):
  File "C:/Users/admin_zj/Desktop/openpose-master/build/python/openpose/openpose.py", line 25, in OpenPose
    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/Release/_openpose.dll')
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
It looks like it's not found ‘_openpose.dll'

**Comment by zj6362295** [comment]
Thanks，now I can use it

**Comment by TharinduRangana** [comment]
zj6362295,
hey could you please help me to run the openpose python scripts. could you please mention all the steps you did to run python scripts.

**Comment by flpymonkey** [comment]
I have also been having trouble running the python API for windows.

After verifying that the source code compiled and the demo worked, I am now trying to use the Python API. However, by following the instructions ([found here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md)) and trying to run `1_extract_pose.py`, I receive the following error:

`Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?`
This error is thrown as a result of a failed import (lines 18-21 in `1_extract_pose.py`). I already have `BUILD_PYTHON` set to ON and have re built the project using Cmake and VS2015.

I thought that this resulted from something wrong with the path, so I hardcoded the path to the `build/python/openpose/` directory and then got a different error on line 37 when it says it can't find the OpenPose class (despite the import appearing to work).
However, when printing `dir(openpose)` after the import to the absolute system path, OpenPose does not appear in the list. 

Additionally, I tried adding the absolute path to my environment variables, and then using `import openpose` in python3.6 IDLE and received the following error: 

```
Traceback (most recent call last):
  File "C:\Users\bencj\Documents\Development\openpose\build\python\openpose\openpose.py", line 27, in OpenPose
    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/Release/_openpose.dll')
  File "C:\Users\bencj\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import openpose
  File "C:\Users\bencj\Documents\Development\openpose\build\python\openpose\openpose.py", line 17, in <module>
    class OpenPose(object):
  File "C:\Users\bencj\Documents\Development\openpose\build\python\openpose\openpose.py", line 29, in OpenPose
    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/Debug/_openpose.dll')
  File "C:\Users\bencj\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```
Which once again appears to be an issue with the paths used for load_libraries. Has anyone else had similar issues? Am I potentially doing something wrong when running cmake and compiling through VS2015? I followed the setup instructions exactly and have confirmed that the demo works.

**Comment by JasOlean** [comment]
I got the same error. BUILD_PYTHON=ON and there is no tutorial_python folder in openpose/build/examples/ directory. this tutorial_python folder is in openpose/examples/ directory. And I read all solutions but I do not understand clearly. Please let me know there is a solution for that.
